spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/bank_db
    username: postgres
    password: aa
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
management:
  security:
    enabled: false